name: Swift

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: swift build -v -c debug
    - name: Build (Release)
      run: swift build -v -c release
    - name: Test (Debug)
      run: swift test -v --configuration debug --enable-test-discovery
    - name: Test (Release)
      run: swift test -v --configuration release -Xswiftc -enable-testing
      
